config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails.application.routes.draw do
  get 'welcome/index', to: 'welcome#index'
  get 'welcome/next', to: 'welcome#next'
  get 'welcome/next/sub1', to: 'welcome#sub1'
  get 'welcome/next/sub2', to: 'welcome#sub2'
  get 'welcome/next2', to: 'welcome#next2'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end

    def next
    end

    def sub1
    end

    def sub2
    end

    def next2
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/next_helper.rb
module NextHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TylerWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, World!</h1>
<p>Welcome to my Ruby on Rails website!</p>
<%= link_to 'Next', welcome_next_path, class: "btn btn-primary" %>
<%= link_to 'Next2', welcome_next2_path, class: "btn btn_primary" %>

app/views/welcome/next.html.erb
<h1>Next Page</h1>
<p>Next page content goes here.</p>
<%= link_to 'Subpage1', welcome_next_sub1_path, class: 'btn' %>
<%= link_to 'Subpage2', welcome_next_sub2_path, class: 'btn' %>

app/views/welcome/next2.html.erb
<h1>Next2 Page</h1>
<p>Next2 page content goes here.</p>

app/views/welcome/sub1.html.erb
<h1>SUB1</h1>
<p>SUB1 page content goes here.</p>

app/views/welcome/sub2.html.erb
<h1>SUB2</h1>
<p>SUB2 page content goes here.</p>